//! `laser` - Spellcaster R4: ILDA frames, scan optimization, mandatory safety,
//! `.ild` files and multi-feed output to Ether Dream, Helios and IDN.
//!
//! Self-contained crate: it depends on `protocols` only for the Ether Dream beacon already
//! implemented in `protocols::netscan`. It does not know the engine, the GUI or the timeline.
//!
//! The behavior reference is the Python package `spellcaster/protocols/ilda/`: the numbers of
//! `optimize`/`safety` and the `.ild` bytes must be identical (fixtures in `tests/fixtures/`,
//! generated by `tests/gen_fixtures.py`).
//!
//! ```no_run
//! use laser::{Dac, EtherDream, Feed, Safety, ild};
//! let dac = EtherDream::connect("192.168.0.50", 1800).unwrap();
//! let feed = Feed::start(Box::new(dac), 30_000, 2, Safety::default()).unwrap();
//! for f in ild::read(std::path::Path::new("shows/logo.ild")).unwrap() {
//!     feed.push(&f.points);
//! }
//! ```

pub mod dac;
pub mod feed;
pub mod frame;
pub mod ild;
pub mod trace;

pub use dac::etherdream::{Emulator, EtherDream};
pub use dac::idn::Idn;
pub use dac::Dac;
pub use feed::{Feed, FeedStats, Transform};
pub use frame::{bbox, optimize, optimize_into, Frame, Point, Safety};
