/* Spellcaster LASER · rodada 5 · o app: estado do aparelho, parede (render 2D → textura), cena (mat/body/optics/
   beam/pino), splash (câmera na parede → contorno → brilho → voa para a traseira), câmera SolidWorks, ações com
   bindings de tecla e MIDI, painéis, OLED, voto. Rodada 6: cada ação leva o endereço do registry (laser/1/...) e o
   contexto; o pino 3 do Pino abre o ORQUESTRADOR (manifesto, rotas, graph do .spell). Uma fonte só das ações: aqui. */
(function () {
  "use strict";
  var $ = function (s) { return document.querySelector(s); }, reduced = matchMedia("(prefers-reduced-motion: reduce)").matches;
  /* ---------- áudio ---------- */
  var AC = null; function ac() { if (!AC) AC = new (window.AudioContext || window.webkitAudioContext)(); if (AC.state === "suspended") AC.resume(); return AC; }
  function tone(f, t0, d, type, g) { var a = ac(), o = a.createOscillator(), v = a.createGain(); o.type = type || "square"; o.frequency.value = f; v.gain.setValueAtTime(0, t0); v.gain.linearRampToValueAtTime(g || .08, t0 + .01); v.gain.exponentialRampToValueAtTime(.0005, t0 + d); o.connect(v); v.connect(a.destination); o.start(t0); o.stop(t0 + d + .02); }
  function jingle() { try { var t = ac().currentTime + .05, seq = [[330, .09], [440, .09], [554, .09], [659, .09], [880, .18], [659, .09], [880, .3]], i; for (i = 0; i < seq.length; i++) { tone(seq[i][0], t, seq[i][1], "square", .07); tone(seq[i][0] / 2, t, seq[i][1], "triangle", .05); t += seq[i][1]; } for (i = 0; i < 24; i++) tone(1760 + Math.sin(i) * 300, t - .9 + i * .03, .04, "square", .02); } catch (e) {} }
  function blip(f) { try { var t = ac().currentTime; tone(f || 1200, t, .05, "square", .05); } catch (e) {} }
  function chord() { try { var t = ac().currentTime; [220, 277, 330, 440].forEach(function (f, i) { tone(f, t + i * .04, .7, "triangle", .06); }); } catch (e) {} }
  function click() { try { var t = ac().currentTime; tone(3000, t, .02, "square", .04); tone(180, t, .04, "triangle", .06); } catch (e) {} }

  /* ---------- estado ---------- */
  var S = { mode: "splash", t0: performance.now(), play: true, key: false, lock: true, power: true, kpps: 30000, buffer: 3, speed: 1, size: 1, fog: .85, frame: 0, pos: 0, show: null, name: "", cam: "rear", lim: { r: 1, g: 1, b: 1 }, gam: { r: 1, g: 1, b: 1 }, dmx: 1, shut: false, net: { ndi: false, spout: false, artnet: false, sacn: true }, page: 0, field: 0, temp: 31, mem: null, tip: {}, dim: 1, armedOnce: false };
  try { S.mem = JSON.parse(localStorage.getItem("sc-laser") || "null"); if (S.mem && S.mem.kpps) S.kpps = S.mem.kpps; } catch (e) {}
  var demo = ILDA.parse(ILDA.write(ILDA.demo()).buffer); S.show = demo.frames; S.name = "demo.ild · " + demo.frames.length + " frames";
  function fps() { var f = S.show[S.frame]; return f && f.length ? S.kpps / f.length : 0; }
  function armed() { return S.power && S.key; } function live() { return armed() && S.lock && !S.shut; }
  function remember() { try { localStorage.setItem("sc-laser", JSON.stringify({ kpps: S.kpps, name: S.name, when: Date.now() })); } catch (e) {} }

  /* ---------- parede ---------- */
  var WC = document.createElement("canvas"); WC.width = 1024; WC.height = 640; var wx = WC.getContext("2d"), WW = 1024, WH = 640, galvo = null, lit = [], gpos = [0, 0];
  function toScreen(p) { var sc = S.size * WH * .3 / 32767; return [WW * .5 + p.x * sc, WH * .5 - p.y * sc]; }
  function cc(p) { var g = S.gam, l = S.lim; return [Math.round(255 * l.r * Math.pow(p.r / 255, g.r)), Math.round(255 * l.g * Math.pow(p.g / 255, g.g)), Math.round(255 * l.b * Math.pow(p.b / 255, g.b))]; }
  function col(c, a) { return "rgba(" + c[0] + "," + c[1] + "," + c[2] + "," + a + ")"; }
  function drawFrame(f, from, count) { var N = f.length, lag = Math.max(.3, Math.min(1, 1.3 - S.kpps / 40000)) * S.speed, i; lit = [];
    wx.globalCompositeOperation = "lighter"; wx.lineCap = "round"; wx.lineJoin = "round"; wx.shadowBlur = 18; var prev = galvo || toScreen(f[(from - 1 + N) % N]);
    for (i = 0; i < count; i++) { var p = f[(from + i) % N], s = toScreen(p), cur = [prev[0] + (s[0] - prev[0]) * Math.min(1, lag), prev[1] + (s[1] - prev[1]) * Math.min(1, lag)];
      if (!p.bl && (i > 0 || galvo)) { var c = cc(p); if (c[0] + c[1] + c[2] > 12) { wx.strokeStyle = col(c, .85); wx.shadowColor = col(c, 1); wx.lineWidth = 3; wx.beginPath(); wx.moveTo(prev[0], prev[1]); wx.lineTo(cur[0], cur[1]); wx.stroke(); lit.push([cur, c]); } } prev = cur; }
    galvo = prev; gpos = [(prev[0] / WW - .5) * 2, (.5 - prev[1] / WH) * 2]; wx.shadowBlur = 24; wx.shadowColor = "#fff"; wx.fillStyle = "rgba(255,255,255,.9)"; wx.beginPath(); wx.arc(prev[0], prev[1], 3, 0, 7); wx.fill(); wx.shadowBlur = 0; wx.globalCompositeOperation = "source-over"; }
  function parked(now, a) { var c = toScreen({ x: 0, y: 0 }); galvo = null; gpos = [0, 0]; wx.globalCompositeOperation = "lighter"; wx.shadowBlur = 34; wx.shadowColor = "#FF2A1A"; wx.fillStyle = "rgba(255,42,26," + (a == null ? .6 + .4 * Math.sin(now / 90) : a) + ")"; wx.beginPath(); wx.arc(c[0], c[1], 4, 0, 7); wx.fill(); wx.shadowBlur = 0; wx.globalCompositeOperation = "source-over"; lit = [[c, [255, 42, 26]]]; }
  function wallTick(now, dt) { wx.globalCompositeOperation = "source-over"; wx.fillStyle = "rgba(0,0,0," + (reduced ? .6 : .3) + ")"; wx.fillRect(0, 0, WW, WH); var f = S.show[S.frame]; if (!S.power) { lit = []; return; }
    if (live() && f && f.length) { var N = f.length, adv = S.kpps * dt; if (S.play) { S.pos += adv; while (S.pos >= N) { S.pos -= N; S.frame = (S.frame + 1) % S.show.length; N = S.show[S.frame].length; f = S.show[S.frame]; } } else S.pos = (S.pos + adv) % N; var from = Math.floor(S.pos), count = Math.min(N, Math.ceil(adv)); drawFrame(f, (from - count + N) % N, count); } else parked(now); }
  // splash: o galvo contorna SPELLCASTER LASER, laço a laço; cada letra fechada é revelada; no fim tudo brilha
  var SP = { loops: [], len: 0, pos: 0, li: 0, pi: 0, done: [], flew: false, last: null };
  function fillDone(alpha, glow) { if (!SP.done.length) return; wx.save(); wx.globalCompositeOperation = "lighter"; wx.beginPath(); SP.done.forEach(function (l) { wx.moveTo(l[0][0], l[0][1]); for (var i = 1; i < l.length; i++) wx.lineTo(l[i][0], l[i][1]); wx.closePath(); }); wx.shadowBlur = glow || 0; wx.shadowColor = "#38FF5C"; wx.fillStyle = "rgba(56,255,92," + alpha + ")"; wx.fill("evenodd"); wx.restore(); }
  function wallSplash(now, dt) { var t = (now - S.t0) / 1000, T = SP;
    if (t < .8) { wx.fillStyle = "rgba(0,0,0,.35)"; wx.fillRect(0, 0, WW, WH); parked(now); return; }
    if (t < 4.8 && T.loops.length) { if (!T.cleared) { T.cleared = true; wx.globalCompositeOperation = "source-over"; wx.fillStyle = "#000"; wx.fillRect(0, 0, WW, WH); } var target = Math.min(T.len, (t - .8) / 4 * T.len), pt = null; wx.globalCompositeOperation = "lighter"; wx.lineCap = "round"; wx.lineJoin = "round"; wx.lineWidth = 3; wx.strokeStyle = "rgba(56,255,92,.9)"; wx.shadowBlur = 14; wx.shadowColor = "#38FF5C";
      while (T.pos < target && T.li < T.loops.length) { var L = T.loops[T.li], a = L[T.pi], b = L[T.pi + 1]; if (!b) { T.done.push(L); T.li++; T.pi = 0; T.last = null; continue; } var sl = Math.hypot(b[0] - a[0], b[1] - a[1]), room = target - T.pos, k = Math.min(1, room / Math.max(1e-6, sl)); pt = [a[0] + (b[0] - a[0]) * k, a[1] + (b[1] - a[1]) * k]; var from = T.last || a; wx.beginPath(); wx.moveTo(from[0], from[1]); wx.lineTo(pt[0], pt[1]); wx.stroke(); if (k >= 1) { T.pos += sl; T.pi++; T.last = null; } else { T.pos = target; T.last = pt; } }
      wx.shadowBlur = 0; wx.globalCompositeOperation = "source-over"; if (T.done.length > (T.filled || 0)) { fillDone(.14); T.filled = T.done.length; }
      if (pt) { wx.globalCompositeOperation = "lighter"; wx.shadowBlur = 26; wx.shadowColor = "#fff"; wx.fillStyle = "rgba(255,255,255,.9)"; wx.beginPath(); wx.arc(pt[0], pt[1], 3, 0, 7); wx.fill(); wx.shadowBlur = 0; wx.globalCompositeOperation = "source-over"; lit = [[pt, [120, 255, 150]]]; gpos = [(pt[0] / WW - .5) * 2, (.5 - pt[1] / WH) * 2]; } return; }
    if (t < 5.8) { if (T.li < T.loops.length) { T.done = T.loops.slice(); T.li = T.loops.length; } var k = (t - 4.8); fillDone(.05 + .25 * Math.sin(Math.min(1, k) * Math.PI) * (1 + Math.sin(k * 40) * .3), 40 * Math.sin(Math.min(1, k) * Math.PI)); lit = []; return; }
    // laser apaga, a parede esfria, a luz da sala baixa, a câmera voa para a traseira
    wx.fillStyle = "rgba(0,0,0,.08)"; wx.fillRect(0, 0, WW, WH); lit = []; S.dim = .55; if (!T.flew) { T.flew = true; setCam("rear", 2.2); } if (t > 7.6) start(); }

  /* ---------- cena ---------- */
  var stage = $("#stage"), gl = $("#gl"), R = new THREE.WebGLRenderer({ canvas: gl, antialias: false, powerPreference: "high-performance" }), scene = new THREE.Scene(), cam = new THREE.PerspectiveCamera(42, 1, .02, 60), pick = [];
  R.setPixelRatio(Math.min(2, devicePixelRatio)); scene.background = new THREE.Color(0x020306); scene.fog = new THREE.FogExp2(0x03040a, .12);
  var X = MAT(THREE, R); scene.environment = X.env();
  var sun = new THREE.SpotLight(0xfff4e6, 90, 9, .42, .7, 1.4); sun.position.set(1.4, 3.2, 1.2); sun.target.position.set(0, .35, 0); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); sun.shadow.bias = -.0004; sun.shadow.radius = 4; scene.add(sun, sun.target);
  var fill = new THREE.PointLight(0x38ff5c, 4, 4, 2); fill.position.set(-.9, .9, .5); scene.add(fill); var rim = new THREE.PointLight(0xa0c0ff, 8, 5, 2); rim.position.set(.4, 1.2, -1.6); scene.add(rim);
  var inLight = new THREE.PointLight(0xfff0dc, 0, 1.2, 2); inLight.position.set(.05, .62, 0); scene.add(inLight);
  var B = BODY(THREE, X, scene, pick), O = OPTICS(THREE, X, B.body, pick);
  var wallTex = new THREE.CanvasTexture(WC); wallTex.minFilter = THREE.LinearFilter; wallTex.encoding = THREE.sRGBEncoding; var proj = new THREE.Mesh(new THREE.PlaneGeometry(8, 5), new THREE.MeshBasicMaterial({ map: wallTex, transparent: true, blending: THREE.AdditiveBlending, depthWrite: false })); proj.position.set(0, 2.2, -5); scene.add(proj);
  var beamsOut = BEAM(THREE, scene, 160, .006, .028), beamsIn = BEAM(THREE, scene, 12, .0012, .0045);
  var FC = document.createElement("canvas"); FC.width = FC.height = 128; var fc = FC.getContext("2d"), fg = fc.createRadialGradient(64, 64, 0, 64, 64, 64); fg.addColorStop(0, "rgba(120,140,170,1)"); fg.addColorStop(1, "rgba(120,140,170,0)"); fc.fillStyle = fg; fc.fillRect(0, 0, 128, 128);
  var fogTex = new THREE.CanvasTexture(FC), puffs = []; for (var i = 0; i < 14; i++) { var sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: fogTex, transparent: true, opacity: .05, blending: THREE.AdditiveBlending, depthWrite: false })); sp.position.set((Math.random() - .5) * 5, .4 + Math.random() * 2.4, -.5 - Math.random() * 4.5); var sc = 1.5 + Math.random() * 2.5; sp.scale.set(sc, sc, 1); sp.userData.v = [(Math.random() - .5) * .08, (Math.random() - .5) * .03]; scene.add(sp); puffs.push(sp); }
  var composer = new THREE.EffectComposer(R); composer.renderTarget1.texture.encoding = composer.renderTarget2.texture.encoding = THREE.sRGBEncoding; composer.addPass(new THREE.RenderPass(scene, cam)); var bloom = new THREE.UnrealBloomPass(new THREE.Vector2(1024, 760), .5, .45, .82); composer.addPass(bloom); var fxaa = new THREE.ShaderPass(THREE.FXAAShader); composer.addPass(fxaa);

  /* ---------- câmera ---------- */
  var ray = new THREE.Raycaster(), mv = new THREE.Vector2(-2, -2), mouse = null, hot = null, tip = $("#tip"), pressed = false;
  function ptr(e) { var r = gl.getBoundingClientRect(); mv.set(((e.clientX - r.left) / r.width) * 2 - 1, -((e.clientY - r.top) / r.height) * 2 + 1); mouse = [e.clientX - r.left, e.clientY - r.top]; return mouse; }
  function hitOf(e) { ptr(e); ray.setFromCamera(mv, cam); var hits = ray.intersectObjects(pick, true); for (var i = 0; i < hits.length; i++) { var h = hits[i].object; while (h && !(h.userData && h.userData.key)) h = h.parent; if (h) return { o: h, p: hits[i].point }; } return null; }
  var CAM = SWCam(THREE, cam, gl, { emptyRotate: true, speed: 5, hit: function (e) { return !!hitOf(e); }, pick: function (e) { ptr(e); ray.setFromCamera(mv, cam); var hs = ray.intersectObjects(scene.children, true).filter(function (h) { return h.object.visible && !h.object.isSprite && h.object.type !== "InstancedMesh"; }); return hs.length ? hs[0].point : null; }, plane: function (e, t) { ptr(e); ray.setFromCamera(mv, cam); var n = cam.getWorldDirection(new THREE.Vector3()), pl = new THREE.Plane().setFromNormalAndCoplanarPoint(n, t), p = new THREE.Vector3(); return ray.ray.intersectPlane(pl, p) ? p : null; } });
  var VIEWS = { show: [[1.5, .95, 1.25], [0, .8, -1.9]], rear: [[.02, .47, .82], [0, .40, .15]], inside: [[.09, .80, .27], [-.02, .38, -.03]], wall0: [[.25, .8, .35], [0, 1.5, -2.6]], wall: [[0, 2.0, .2], [0, 2.2, -5]] }, camSpeed = 5;
  function setCam(k, speed) { S.cam = k; CAM.setView(VIEWS[k][0], VIEWS[k][1]); camSpeed = speed || 5; document.querySelectorAll("#cams [data-a]").forEach(function (b) { b.classList.toggle("on", b.dataset.a === "cam." + k); }); if (S.mode === "play") blip(k === "inside" ? 700 : 1000); if (k !== "inside") closePanel(); }
  var CENTER = new THREE.Vector3(0, .40, 0);

  /* ---------- painel ---------- */
  var panel = $("#panel"), pbody = $("#pbody"), pcur = null; panel.querySelector(".x").addEventListener("click", closePanel);
  function closePanel() { panel.classList.remove("on"); pcur = null; $("#cli").textContent = "spell ilda play show.ild --kpps 30"; }
  function esc(s) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;"); }
  function open(title, sub, html, wide, id) { panel.classList.toggle("wide", !!wide); pbody.innerHTML = "<h3>" + title + "</h3><div class='sub'>" + sub + "</div>" + html; panel.classList.add("on"); pcur = id || null; }
  function get(p) { var a = p.split("."), o = S; for (var i = 0; i < a.length; i++) o = o[a[i]]; return o; } function set(p, v) { var a = p.split("."), o = S; for (var i = 0; i < a.length - 1; i++) o = o[a[i]]; o[a[a.length - 1]] = v; }
  var FMT = { kpps: function (v) { return Math.round(v / 1000) + "k"; }, pct: function (v) { return Math.round(v * 100) + "%"; }, gam: function (v) { return "γ " + (+v).toFixed(2); }, n: function (v) { return v; }, x: function (v) { return "×" + (+v).toFixed(2); } }, fmtOf = {};
  function rg(label, path, min, max, step, f) { fmtOf[path] = FMT[f]; return "<div class='row'><span>" + label + "</span><input type='range' data-p='" + path + "' min='" + min + "' max='" + max + "' step='" + step + "' value='" + get(path) + "'><span class='v' data-v='" + path + "'>" + FMT[f](get(path)) + "</span></div>"; }
  panel.addEventListener("input", function (e) { var r = e.target; if (!r.dataset.p) return; set(r.dataset.p, +r.value); panel.querySelector("[data-v='" + r.dataset.p + "']").textContent = fmtOf[r.dataset.p](+r.value); remember(); if (/^(lim|gam)\./.test(r.dataset.p)) { var old = pbody.querySelector(".cv"); if (old) old.replaceWith(curveCanvas()); } Bind.syncAll(); });
  panel.addEventListener("click", function (e) { if (Bind.click(e)) { PANELS.bind(); return; } var c = e.target.closest("[data-copy]"); if (c) { var el = pbody.querySelector("#" + c.dataset.copy); (navigator.clipboard ? navigator.clipboard.writeText(el.textContent) : Promise.reject()).then(function () { c.textContent = "COPIADO"; }, function () { var r = document.createRange(); r.selectNodeContents(el); getSelection().removeAllRanges(); getSelection().addRange(r); c.textContent = "SELECIONADO · CTRL+C"; }); return; } var b = e.target.closest("[data-a]"); if (b) Bind.run(b.dataset.a); });
  function curveCanvas() { var c = document.createElement("canvas"); c.width = 268; c.height = 90; c.className = "cv"; var x = c.getContext("2d"); x.fillStyle = "#050708"; x.fillRect(0, 0, 268, 90); ["r", "g", "b"].forEach(function (k) { x.strokeStyle = { r: "#FF2A1A", g: "#38FF5C", b: "#3A6BFF" }[k]; x.lineWidth = 1.5; x.beginPath(); for (var i = 0; i <= 40; i++) { var t = i / 40, y = S.lim[k] * Math.pow(t, S.gam[k]); x.lineTo(4 + t * 260, 86 - y * 82); } x.stroke(); }); return c; }
  function onoff(a, on, y, n) { return "<button class='lb" + (on ? " on" : "") + "' data-a='" + a + "'>" + (on ? y : n) + "</button>"; }
  var PANELS = {
    ilda: function () { open("ILDA IN", "DB25 · " + S.name, "<pre>frame <b>" + (S.frame + 1) + " / " + S.show.length + "</b> · " + (S.show[S.frame] || []).length + " pts · " + Math.round(fps()) + " fps de frame\nspell ilda play show.ild --kpps " + Math.round(S.kpps / 1000) + "</pre><div class='btns'><button class='lb' data-a='file.open'>ESCOLHER .ILD</button><button class='lb' data-a='demo'>DEMO</button>" + onoff("play.toggle", S.play, "PAUSA", "PLAY") + "</div>" + rg("TAMANHO", "size", .3, 1.3, .01, "pct"), false, "ilda"); },
    ildathru: function () { open("ILDA OUT", "DB25 macho · passa o sinal para o próximo projetor", "<pre>encadeado: <b>nenhum</b>\nspell ilda play show.ild --chain 2</pre>"); },
    rj45: function () { open("NET", "RJ45 · fontes de rede", "<div class='btns'>" + ["ndi", "spout", "artnet", "sacn"].map(function (k) { return onoff("net." + k, S.net[k], k.toUpperCase() + " · ON", k.toUpperCase()); }).join("") + "</div><pre>NDI → ILDA e Spout → ILDA são o conversor <b>FÓSFORO</b> (próxima rodada).\nspell ilda net --ndi \"RESOLUME (out)\"</pre>", false, "rj45"); },
    dmxin: function () { open("DMX IN", "XLR-5 fêmea · endereço e modo", rg("ENDEREÇO", "dmx", 1, 512, 1, "n") + "<pre>modo <b>16 canais</b>: shutter · padrão · tamanho · rotação · X · Y · cor · kpps...\nspell dmx addr " + S.dmx + "</pre>", false, "dmxin"); },
    dmxout: function () { open("DMX OUT", "XLR-5 macho · o Pino está plugado aqui", "<pre>repete o universo para o próximo aparelho\nterminador: <b>não</b> · cabo: <b>Pino</b></pre>"); },
    power: function () { open("AC IN", "powerCON TRUE1 · 100-240 V · 180 W", "<div class='btns'>" + onoff("power.toggle", S.power, "LIGADO · DESLIGAR", "DESLIGADO · LIGAR") + "</div><pre>consumo <b>" + (S.power ? (live() ? "180 W" : "42 W") : "0 W") + "</b> · sem fusível externo: proteção na fonte</pre>", false, "power"); },
    keyswitch: function () { open("CHAVE", "arma a emissão", "<div class='btns'>" + onoff("key.toggle", S.key, "ARMADO · DESARMAR", "DESARMADO · ARMAR") + "</div><pre>" + (S.key ? "diodos ligados, LED EMISSION aceso" : "sem chave não há emissão; a vista SHOW fica trancada") + "\nS no teclado faz o mesmo</pre>", false, "keyswitch"); },
    interlock: function () { open("INTERLOCK", "plugue de segurança", "<div class='btns'>" + onoff("lock.toggle", S.lock, "FECHADO · ABRIR", "ABERTO · FECHAR") + "</div><pre>" + (S.lock ? "circuito fechado: obturador aberto" : "<b>SCAN FAIL</b>: obturador fechado, feixe estacionado") + "</pre>", false, "interlock"); },
    usb: function () { open("USB", "atualização de firmware", "<pre>firmware <b>0.1.2</b> · spell 0.1.2\nspell fw update</pre>"); },
    oled: function () { open("OLED", "menu do painel · encoder gira e aperta · BACK volta", "<pre>página " + (S.page + 1) + "/5: <b>" + PAGES[S.page] + "</b>\nroda do mouse em cima do encoder muda o valor</pre><div class='btns'><button class='lb' data-a='oled.down'>◄</button><button class='lb' data-a='oled.up'>►</button><button class='lb' data-a='oled.ok'>OK</button><button class='lb' data-a='oled.back'>BACK</button></div>", false, "oled"); },
    enc: function () { PANELS.oled(); }, back: function () { Bind.run("oled.back"); PANELS.oled(); },
    fan: function () { open("VENTOINHA", "60 mm axial · aspira pelas aletas", "<pre>diodos <b>" + S.temp.toFixed(0) + " °C</b> · galvos " + (S.temp - 6).toFixed(0) + " °C · fonte " + (S.temp + 4).toFixed(0) + " °C\nrotação: automática · desliga a 65 °C</pre>"); },
    psu: function () { open("FONTE", "48 V · 250 W", "<pre>48,1 V · 3,7 A · <b>" + (S.temp + 4).toFixed(0) + " °C</b>\nspell status</pre>"); },
    galvo: function () { open("GALVOS X/Y", "30 kpps nominal · 40 máx", rg("KPPS", "kpps", 5000, 40000, 500, "kpps") + "<pre>taxa de frame = kpps ÷ pontos · &lt; 25 fps pisca\n&gt; 32 kpps o galvo não acompanha: cantos viram curvas\nspell ilda play --kpps " + Math.round(S.kpps / 1000) + "</pre>", false, "galvo"); },
    galvodrv: function () { open("DRIVER DOS GALVOS", "buffer e velocidade", rg("BUFFER", "buffer", 1, 8, 1, "n") + rg("VELOCIDADE", "speed", .4, 1.6, .01, "x") + "<pre>buffer em frames antes do galvo; velocidade escala o passa-baixa</pre>", false, "galvodrv"); },
    pcb: function () { open("DRIVER DO DIODO", "corrente constante · modulação analógica", "<pre>3 canais · 0-5 V · 100 kHz\nlimite e curva: clique no módulo</pre>"); },
    dac: function () { open("PLACA DAC ILDA", "os conectores traseiros nascem aqui", "<pre>DAC 12 bit X/Y · 8 bit RGB · " + Math.round(S.kpps / 1000) + " kpps\nspell ilda play show.ild</pre>"); },
    dichro: function () { open("DICROICOS", "combinam R, G e B num feixe", "<pre>alinhamento: <b>ok</b> · desvio 0,1 mrad\ndois parafusos de ajuste: não mexa sem chave hexagonal</pre>"); },
    fold: function () { open("ESPELHO DE DOBRA", "HR 99,5 % · manda o feixe para os galvos", "<pre>desvio 0,05 mrad · limpo</pre>"); },
    shutter: function () { open("OBTURADOR", "solenoide · fecha sem chave ou sem interlock", "<div class='btns'>" + onoff("shutter", !S.shut, "ABERTO · FECHAR", "FECHADO · ABRIR") + "</div><pre>estado: <b>" + (live() ? "ABERTO" : "FECHADO") + "</b>\ntempo de fechamento 8 ms\nspell laser shutter " + (S.shut ? "close" : "open") + "</pre>", false, "shutter"); },
    // rodada 6: o laser como módulo do orquestrador; manifesto e graph saem das mesmas definições de Bind.def
    orq: function () { var g = Bind.graph({ cam: S.cam, fog: +S.fog.toFixed(2) }), m = Bind.manifest(); $("#cli").textContent = "spell graph add laser/1 · spell graph wire midi/cc:1:7 laser/1/kpps --filter lag";
      open("ORQUESTRADOR", "laser/1 · módulo do graph · cada binding é uma rota entrada → filtro → endereço", "<div class='eyebrow'>manifesto · design/laser/module.json</div><pre class='js'>" + esc(JSON.stringify(m, null, 1)) + "</pre><div class='eyebrow'>rotas ativas · " + g.wires.length + " · a linha pisca quando a ação roda</div><table>" + g.wires.map(function (w) { return "<tr data-r='" + w.from + "'><td class='k'>" + w.from + "</td><td class='b'>" + (w.filter || "—") + "</td><td class='k'>" + w.to + (w.args ? " <small>" + esc(JSON.stringify(w.args)) + "</small>" : "") + "</td></tr>"; }).join("") + "</table><div class='eyebrow'>graph · trecho do .spell</div><pre class='js' id='gjs'>" + esc(JSON.stringify(g, null, 1)) + "</pre><div class='btns'><button class='lb' data-copy='gjs'>COPIAR</button></div>", true, "orq"); },
    bench: function () { open("MESA ÓPTICA", "alumínio 16 mm · furação M4 a 12,5 mm", "<pre>tudo parafusado nela: módulos, suportes, obturador, galvos\nnada solto dentro da caixa</pre>"); },
    aperture: function () { open("ABERTURA", "classe 4 · 10 W", "<pre><b>PERIGO</b>: 10 W a 445-638 nm\ndivergência 1,2 mrad · diâmetro 5 mm\nzona de exclusão: 3 m acima da plateia</pre>"); },
    front: function () { PANELS.aperture(); }, side: function () { PANELS.fan(); }, lid: function () { setCam("inside"); }, pino: function () { pino.say(); },
    bind: function () { open("BINDINGS", "tecla e MIDI · clique, depois aperte a tecla ou mexa no controlador · Esc cancela", "<div class='btns'><button class='lb' data-a='midi.connect'>MIDI: " + Bind.midi + "</button>" + onoff("cam.reverse", CAM.reverse, "RODA: SOLIDWORKS", "RODA: NORMAL") + "<button class='lb amb' data-a='bind.reset'>RESET</button></div>" + Bind.html(), true, "bind"); },
    nfo: function () { open("SPELLCASTER LASER · RODADA 6", "info · N fecha", "<pre>o programa é o aparelho: portas atrás = menu, tampa aberta = preferências; pino 3 = módulo laser/1 do orquestrador\nparede = kpps ÷ pontos, galvo passa-baixa; feixe em GLSL; câmera SolidWorks; bindings tecla + MIDI\n\nCLI: spell ilda play show.ild --kpps 30\nMCP: ilda.play {file, kpps} · ilda.limit {r,g,b} · bind.learn {action}\n\nGREETZ: PANGOLIN · ETHER DREAM · LSX · KVANT · CHATAIGNE · MADMAPPER\nCRACKED BY FEITIÇARIA iNDUSTRIAL · NO SERIAL NEEDED</pre>", true, "nfo"); } };
  ["r", "g", "b"].forEach(function (k) { PANELS[k] = function () { var nm = { r: "638 nm · 2,5 W", g: "520 nm · 3 W", b: "445 nm · 4,5 W" }[k]; open("MÓDULO " + { r: "VERMELHO", g: "VERDE", b: "AZUL" }[k], nm + " · limite e curva", rg("LIMITE", "lim." + k, 0, 1, .01, "pct") + rg("CURVA", "gam." + k, .5, 2.5, .01, "gam") + "<pre>spell ilda limit --" + k + " " + S.lim[k].toFixed(2) + "</pre>", false, k); pbody.appendChild(curveCanvas()); }; });
  function refresh() { if (pcur && PANELS[pcur]) PANELS[pcur](); }

  /* ---------- OLED ---------- */
  var PAGES = ["DMX ADDR", "NET", "OUTPUT", "STATUS", "ABOUT"], NETS = ["sacn", "artnet", "ndi", "spout"], oc = B.oled.c;
  function oledTurn(d) { click(); if (S.page === 0) S.dmx = Math.max(1, Math.min(512, S.dmx + d)); else if (S.page === 1) S.field = (S.field + d + 4) % 4; else if (S.page === 2) S.kpps = Math.max(5000, Math.min(40000, S.kpps + d * 1000)); B.knob.rotation.z -= d * .35; drawOled(); refresh(); }
  function oledOk() { click(); if (S.page === 1) { var k = NETS[S.field]; S.net[k] = !S.net[k]; } else S.page = (S.page + 1) % PAGES.length; drawOled(); refresh(); }
  function oledBack() { click(); S.page = (S.page + PAGES.length - 1) % PAGES.length; drawOled(); refresh(); }
  function drawOled() { var w = B.oled.w, h = B.oled.h; oc.fillStyle = "#020806"; oc.fillRect(0, 0, w, h); if (!S.power) { B.oled.tex.needsUpdate = true; return; } oc.fillStyle = "#9FF5D0"; oc.shadowColor = "#9FF5D0"; oc.shadowBlur = 4; oc.textBaseline = "middle"; oc.font = "700 22px 'Share Tech Mono'"; oc.textAlign = "left"; var l1, l2; if (S.page === 0) { l1 = "DMX ADDR " + ("00" + S.dmx).slice(-3); l2 = "16CH  " + (live() ? "LIVE" : !S.key ? "KEY OFF" : S.lock ? "STANDBY" : "SCAN FAIL"); } else if (S.page === 1) { l1 = "NET " + NETS.map(function (k, i) { return (i === S.field ? "[" : " ") + (S.net[k] ? "*" : "-") + (i === S.field ? "]" : " "); }).join(""); l2 = NETS[S.field].toUpperCase() + (S.net[NETS[S.field]] ? " ON" : " OFF"); } else if (S.page === 2) { l1 = "OUT " + Math.round(S.kpps / 1000) + " KPPS"; l2 = (S.show[S.frame] || []).length + " PTS " + Math.round(fps()) + " FPS"; } else if (S.page === 3) { l1 = "TEMP " + S.temp.toFixed(0) + "C  " + (S.lock ? "ILK OK" : "ILK OPEN"); l2 = (S.key ? "ARMED " : "SAFE  ") + (live() ? "EMIT" : "SHUT"); } else { l1 = "SPELLCASTER 0.1.2"; l2 = "FEITICARIA IND."; } oc.fillText(l1, 8, 30); oc.fillText(l2, 8, 74); oc.font = "12px 'Share Tech Mono'"; oc.textAlign = "right"; oc.fillText(PAGES[S.page] + " " + (S.page + 1) + "/5", w - 6, 112); oc.shadowBlur = 0; B.oled.tex.needsUpdate = true; }
  drawOled(); setInterval(drawOled, 500);

  /* ---------- ações ---------- */
  function toggleKey() { S.key = !S.key; if (S.key) { blip(1500); S.armedOnce = true; } else chord(); $("#cams [data-a='cam.show']").disabled = !S.key; refresh(); }
  Bind.def("cam.show", "vista SHOW", function () { if (!S.key) { pino.say("Arma a chave primeiro. Sem emissão não tem show; a chave está na traseira, à esquerda.", null, false); blip(300); return; } setCam("show"); }, { key: "1", addr: "laser/1/cam/view", ctx: "view", arg: { view: "show" } });
  Bind.def("cam.rear", "vista TRÁS · menu", function () { setCam("rear"); }, { key: "2", addr: "laser/1/cam/view", ctx: "view", arg: { view: "rear" } });
  Bind.def("cam.inside", "vista DENTRO · preferências", function () { setCam("inside"); }, { key: "3", addr: "laser/1/cam/view", ctx: "view", arg: { view: "inside" } });
  Bind.def("key.toggle", "chave: arma", toggleKey, { key: "S", midi: "note:1:60", get: function () { return S.key; }, addr: "laser/1/arm", ctx: "both" });
  Bind.def("lock.toggle", "interlock", function () { S.lock = !S.lock; if (!S.lock) { chord(); pino.say("SCAN FAIL. Interlock aberto: obturador fechado, feixe estacionado.", null, false); } else blip(1300); refresh(); }, { key: "I", get: function () { return S.lock; }, addr: "laser/1/interlock", ctx: "value" });
  Bind.def("power.toggle", "energia", function () { S.power = !S.power; if (!S.power) chord(); else blip(900); drawOled(); refresh(); }, { key: "P", get: function () { return S.power; }, addr: "laser/1/power", ctx: "both" });
  Bind.def("play.toggle", "play / pausa", function () { S.play = !S.play; blip(); refresh(); }, { key: "Space", midi: "note:1:62", get: function () { return S.play; }, addr: "laser/1/play", ctx: "both", needs: "arm" });
  Bind.def("kpps.down", "kpps −1k", function () { S.kpps = Math.max(5000, S.kpps - 1000); remember(); refresh(); }, { key: "[", addr: "laser/1/kpps", ctx: "action", arg: { step: -1000 } });
  Bind.def("kpps.up", "kpps +1k", function () { S.kpps = Math.min(40000, S.kpps + 1000); remember(); refresh(); }, { key: "]", addr: "laser/1/kpps", ctx: "action", arg: { step: 1000 } });
  Bind.def("kpps", "kpps (fader)", function (v) { S.kpps = Math.round(5000 + v * 35000); remember(); refresh(); }, { type: "cc", midi: "cc:1:7", get: function () { return (S.kpps - 5000) / 35000; }, addr: "laser/1/kpps", ctx: "both", t: "int", range: [5000, 40000], unit: "pps" });
  Bind.def("size", "tamanho (fader)", function (v) { S.size = .3 + v; refresh(); }, { type: "cc", midi: "cc:1:8", get: function () { return S.size - .3; }, addr: "laser/1/geo/scale", ctx: "mapping", range: [.3, 1.3] });
  ["r", "g", "b"].forEach(function (k, i) { Bind.def("lim." + k, "limite " + { r: "vermelho", g: "verde", b: "azul" }[k] + " (fader)", function (v) { S.lim[k] = v; refresh(); }, { type: "cc", midi: "cc:1:" + (9 + i), get: function () { return S.lim[k]; }, addr: "laser/1/limit/" + k, ctx: "mapping" });
    Bind.def("curve." + k, "curva " + { r: "vermelho", g: "verde", b: "azul" }[k] + " (fader)", function (v) { S.gam[k] = .5 + v * 2; refresh(); }, { type: "cc", get: function () { return (S.gam[k] - .5) / 2; }, addr: "laser/1/curve/" + k, ctx: "mapping", range: [.5, 2.5] }); });
  Bind.def("dmx.addr", "endereço DMX (fader)", function (v) { S.dmx = Math.round(1 + v * 511); drawOled(); refresh(); }, { type: "cc", get: function () { return (S.dmx - 1) / 511; }, addr: "laser/1/dmx/addr", ctx: "mapping", t: "int", range: [1, 512] });
  Bind.def("queue", "fila do galvo (fader)", function (v) { S.buffer = Math.round(1 + v * 7); refresh(); }, { type: "cc", get: function () { return (S.buffer - 1) / 7; }, addr: "laser/1/queue", ctx: "mapping", t: "int", range: [1, 8], unit: "frames" });
  Bind.def("shutter", "obturador", function () { S.shut = !S.shut; if (S.shut) chord(); else blip(1300); refresh(); }, { midi: "note:1:64", get: function () { return !S.shut; }, addr: "laser/1/shutter", ctx: "both", needs: "arm" });
  Bind.def("temp", "temperatura", null, { get: function () { return +S.temp.toFixed(1); }, addr: "laser/1/temp", ctx: "value", unit: "°C" });
  Bind.def("fps", "fps real", null, { get: function () { return +fps().toFixed(1); }, addr: "laser/1/fps", ctx: "value", unit: "Hz" });
  Bind.def("points", "pontos por frame", null, { get: function () { return (S.show[S.frame] || []).length; }, addr: "laser/1/points", ctx: "value", t: "int", unit: "pts" });
  Bind.def("emitting", "emitindo", null, { get: live, addr: "laser/1/emitting", ctx: "value" });
  Bind.def("fog", "névoa (fader)", function (v) { S.fog = v; }, { type: "cc", get: function () { return S.fog; }, addr: "laser/1/cam/fog", ctx: "view" });
  Bind.def("file.open", "abrir .ild", function () { $("#file").click(); }, { key: "O" }); // sem endereço: o diálogo é UI; a rota só existe com arquivo (demo → laser/1/clip {file})
  Bind.def("demo", "demo.ild", function () { S.show = demo.frames; S.frame = 0; S.pos = 0; S.name = "demo.ild · " + demo.frames.length + " frames"; refresh(); pino.say("Demo de volta: túnel, pentagrama e a fita.", null, false); }, { key: "D", addr: "laser/1/clip", ctx: "action", arg: { file: "demo.ild" } });
  ["ndi", "spout", "artnet", "sacn"].forEach(function (k) { Bind.def("net." + k, "rede: " + k.toUpperCase(), function () { S.net[k] = !S.net[k]; blip(1000); drawOled(); refresh(); if (S.net[k] && (k === "ndi" || k === "spout")) pino.say(k.toUpperCase() + " ligado, mas o conversor para ILDA é a próxima rodada: o FÓSFORO, um monitor de rack nesta porta.", null, false); }, { get: function () { return S.net[k]; }, addr: "laser/1/net/" + k, ctx: "both" }); });
  Bind.def("oled.up", "OLED: encoder +", function () { oledTurn(1); }); Bind.def("oled.down", "OLED: encoder −", function () { oledTurn(-1); }); Bind.def("oled.ok", "OLED: OK", oledOk); Bind.def("oled.back", "OLED: BACK", oledBack, { key: "Backspace" });
  Bind.def("nfo", "info", function () { if (pcur === "nfo") closePanel(); else PANELS.nfo(); }, { key: "N" });
  Bind.def("bind", "bindings", function () { if (pcur === "bind") closePanel(); else PANELS.bind(); }, { key: "B" });
  Bind.def("orq", "orquestrador", function () { if (pcur === "orq") closePanel(); else PANELS.orq(); });
  Bind.def("esc", "fecha painel", function () { closePanel(); pino.hide(); }, { key: "Escape" });
  Bind.def("midi.connect", "MIDI: conectar", function () { Bind.connect(); }); Bind.def("bind.reset", "bindings: reset", function () { Bind.reset(); });
  Bind.def("cam.reverse", "roda: sentido SolidWorks", function () { CAM.reverse = !CAM.reverse; try { localStorage.setItem("sc-laser-wheel", CAM.reverse ? "1" : "0"); } catch (e) {} refresh(); }, { get: function () { return CAM.reverse; } }); try { if (localStorage.getItem("sc-laser-wheel") === "0") CAM.reverse = false; } catch (e) {}
  var d15 = Math.PI / 12; [["L", "ArrowLeft", d15, 0], ["R", "ArrowRight", -d15, 0], ["U", "ArrowUp", 0, d15], ["D", "ArrowDown", 0, -d15]].forEach(function (a) { Bind.def("cam.rot" + a[0], "câmera: gira 15° " + a[0], function () { CAM.rotate(a[2], a[3]); }, { key: a[1] }); Bind.def("cam.rot90" + a[0], "câmera: gira 90° " + a[0], function () { CAM.rotate(a[2] * 6, a[3] * 6); }, { key: "Shift+" + a[1] }); Bind.def("cam.pan" + a[0], "câmera: pan " + a[0], function () { CAM.pan(a[2] * -400, a[3] * 400); }, { key: "Ctrl+" + a[1] }); });
  Bind.def("cam.fit", "câmera: enquadra", function () { CAM.fit(CENTER, .32); }, { key: "F" });
  [["front", "1"], ["back", "2"], ["left", "3"], ["right", "4"], ["top", "5"], ["bottom", "6"], ["iso", "7"]].forEach(function (v) { Bind.def("cam." + v[0], "vista padrão: " + v[0], function () { CAM.std(v[0], CENTER, .32); }, { key: "Ctrl+" + v[1] }); });
  Bind.def("cam.zoomIn", "câmera: zoom +", function () { CAM.zoom(.8); }, { key: "Z" }); Bind.def("cam.zoomOut", "câmera: zoom −", function () { CAM.zoom(1.25); }, { key: "Shift+Z" });
  Bind.onChange(function () { if (pcur === "bind") PANELS.bind(); var l = Bind.last(); if (pcur === "orq" && l) ["key", "midi"].forEach(function (src) { var k = Bind.keyOf(l, src), r = k && pbody.querySelector("[data-r='" + src + "/" + k + "']"); if (r) { r.classList.remove("hit"); void r.offsetWidth; r.classList.add("hit"); } }); $("#midi").textContent = "MIDI " + Bind.midi + (Bind.learnState() ? " · LEARN: aperte a tecla ou mexa no controlador" : ""); });
  $("#midi").textContent = "MIDI " + Bind.midi;
  document.querySelectorAll("#cams [data-a]").forEach(function (b) { b.addEventListener("click", function () { if (S.mode === "splash") return; Bind.run(b.dataset.a); }); });

  /* ---------- interação 3D ---------- */
  function glow(o, on) { if (!o) return; o.traverse(function (mm) { if (mm.material && mm.material.emissive) { if (on) { if (mm.userData.orig) return; mm.userData.orig = mm.material; mm.material = mm.material.clone(); mm.material.emissive.setHex(0x38ff5c); mm.material.emissiveIntensity = .45; } else if (mm.userData.orig) { mm.material = mm.userData.orig; mm.userData.orig = null; } } }); }
  gl.addEventListener("pointermove", function (e) { var p = ptr(e); if (CAM.dragging() || S.mode === "splash") { tip.style.display = "none"; return; } var h = hitOf(e), o = h ? h.o : null; if (o !== hot) { glow(hot, false); hot = o; glow(hot, true); if (hot && /^pino\./.test(hot.userData.key)) pino.say(hot.userData.label, null, false); }
    if (hot) { tip.style.display = "block"; tip.textContent = hot.userData.label; tip.style.left = (p[0] + 14) + "px"; tip.style.top = (p[1] + 14) + "px"; gl.style.cursor = "pointer"; } else { tip.style.display = "none"; gl.style.cursor = "grab"; } });
  gl.addEventListener("pointerdown", function (e) { pressed = e.button === 0; });
  gl.addEventListener("pointerup", function (e) { if (!pressed || e.button !== 0) return; pressed = false; if (CAM.dragging()) return; if (S.mode === "splash") { skipSplash(); return; } if (!hot) return; var k = hot.userData.key; blip(1100);
    if (k === "keyswitch") { toggleKey(); } else if (k === "interlock") { Bind.run("lock.toggle"); } else if (k === "power") { Bind.run("power.toggle"); } else if (k === "enc") { oledOk(); } else if (k === "back") { oledBack(); } else if (k === "lid") { setCam("inside"); return; } else if (k === "pino.bye") { pino.bye(); return; } else if (/^pino\./.test(k)) { onPin(k.slice(5)); return; } else if (k === "pino") { pino.say(); return; }
    if (/^(power|keyswitch|interlock|dmx|ilda|rj45|usb|oled|enc|back|fan)/.test(k) && S.cam === "show") setCam("rear"); if (/^(psu|galvo|pcb|dac|dichro|fold|shutter|bench|r|g|b)$/.test(k) && S.cam !== "inside") setCam("inside"); (PANELS[k] || function () {})(); });
  gl.addEventListener("wheel", function (e) { if (hot && hot.userData.key === "enc") { e.stopImmediatePropagation(); e.preventDefault(); oledTurn(e.deltaY < 0 ? 1 : -1); } }, { passive: false, capture: true });
  gl.addEventListener("dragover", function (e) { e.preventDefault(); stage.classList.add("dz"); }); gl.addEventListener("dragleave", function () { stage.classList.remove("dz"); });
  gl.addEventListener("drop", function (e) { e.preventDefault(); stage.classList.remove("dz"); loadFile(e.dataTransfer.files[0]); }); $("#file").addEventListener("change", function () { loadFile(this.files[0]); this.value = ""; });
  function loadFile(f) { if (!f) return; var r = new FileReader(); r.onload = function () { try { var d = ILDA.parse(r.result); if (!d.frames.length) throw 0; S.show = d.frames; S.frame = 0; S.pos = 0; S.name = f.name + " · " + d.frames.length + " frames"; if (S.mode === "splash") skipSplash(); setCam("rear"); PANELS.ilda(); remember(); pino.say("Entrou pela ILDA IN: " + f.name + ", " + d.frames.length + " frames, " + d.frames[0].length + " pontos no primeiro. " + (d.frames[0].length > 1200 ? "Denso. Se piscar, abre a tampa e sobe os kpps no galvo." : "Leve. Vai voar.") + (S.key ? "" : " Arma a chave para ver na parede."), null, false); } catch (x) { pino.say("Isso não é ILDA. Formato 2 (só paleta) eu pulo, 0/1/4/5 eu leio.", null, false); } }; r.readAsArrayBuffer(f); }

  /* ---------- Pino ---------- */
  var pino = Pino3D.build(THREE, X, scene, pick, stage, cam, { on: onPin });
  function onPin(k) { blip(1000); if (k === "ilda") { setCam("rear"); PANELS.ilda(); pino.say("ILDA IN, atrás. Solta o .ild na porta ou escolhe no painel.", null, false); } else if (k === "ndi") { setCam("rear"); PANELS.rj45(); pino.say("A porta NET. NDI e Spout viram ILDA no FÓSFORO, próxima rodada.", null, false); } else if (k === "orq") { setCam("rear"); PANELS.orq(); pino.say("O laser virou o nó laser/1 do graph. Cada binding é uma rota: tecla ou MIDI entra, filtro no meio, endereço na saída. O PATCHBAY desenha isto com jacks de latão.", null, false); } else if (k === "cues") { setCam("rear"); PANELS.dmxin(); pino.say("Cenas e cues chegam pelo DMX IN. O TEATRO DE PAPEL vem depois.", null, false); } else if (k === "nfo") PANELS.nfo(); else if (k === "bye") pino.bye(); pino.current(k); }
  pino.current("ilda");
  function tips() { var F = fps(), f = S.show[S.frame]; if (S.mode !== "play" || !f) return; var flick = live() && F > 0 && F < 25, slow = S.kpps > 32000;
    if (flick && !S.tip.flick) { S.tip.flick = true; pino.say("Tá piscando: " + f.length + " pontos a " + Math.round(S.kpps / 1000) + " kpps dá " + Math.round(F) + " fps. Abre a tampa e mexe no galvo.", null, false); } if (!flick) S.tip.flick = false;
    if (slow && !S.tip.slow) { S.tip.slow = true; pino.say("A " + Math.round(S.kpps / 1000) + " kpps o galvo não acompanha: os cantos viraram curvas.", null, false); } if (!slow) S.tip.slow = false; }

  /* ---------- splash / início ---------- */
  function start() { if (S.mode !== "splash") return; S.mode = "play"; $("#splash").classList.add("off"); S.dim = .55; setCam("rear", 5); setTimeout(function () { pino.say(S.mem ? "Da última vez: " + Math.round(S.mem.kpps / 1000) + " kpps" + (S.mem.name ? ", " + S.mem.name.split(" · ")[0] : "") + ". A traseira é o menu: arma a chave e a vista SHOW libera. B abre os bindings." : "Parece que você está tentando fazer um show de laser. A traseira é o menu. Arma a chave (à esquerda) e a vista SHOW libera. Puxa um pino."); }, 900); }
  function skipSplash() { if (S.mode !== "splash") return; jingle(); start(); }
  document.addEventListener("keydown", function (e) { if (S.mode === "splash" && e.target.tagName !== "TEXTAREA") { skipSplash(); } }, true);

  /* ---------- tick ---------- */
  var last = performance.now(), W = 0, H = 0, T0 = performance.now(), lidT = 0, rearI = 0, segsW = [], tmpV = new THREE.Vector3();
  function size() { if (stage.clientWidth !== W || stage.clientHeight !== H) { W = stage.clientWidth; H = stage.clientHeight; var pr = R.getPixelRatio(); R.setSize(W, H, false); composer.setSize(W, H); bloom.resolution.set(W, H); fxaa.uniforms.resolution.value.set(1 / (W * pr), 1 / (H * pr)); cam.aspect = W / H; cam.updateProjectionMatrix(); } }
  function tick(now) { size(); var dt = Math.min(.1, (now - last) / 1000); last = now; var t = (now - T0) / 1000;
    if (S.mode === "splash") wallSplash(now, dt); else wallTick(now, dt); wallTex.needsUpdate = true;
    var want = S.cam === "inside" ? 1 : 0; lidT += (want - lidT) * Math.min(1, dt * 3); var sT = Math.min(1, lidT / .45), lT = Math.max(0, (lidT - .4) / .6); B.screws.forEach(function (s, i) { s.position.y = .004 + sT * .05; s.rotation.y = sT * 12 + i; }); B.lid.rotation.x = -lT * 1.9;
    CAM.update(dt * camSpeed / 5); rearI += (((S.cam === "rear" && S.mode === "play") ? 14 : 0) - rearI) * Math.min(1, dt * 3); B.rearLight.intensity = rearI; inLight.intensity = .35 * lidT; sun.intensity = 90 * S.dim; B.wallLight.intensity = 14 * S.dim;
    // feixes externos: abertura → pontos acesos da parede
    var on = S.power && (S.mode === "splash" || live()), step = Math.max(1, Math.ceil(lit.length / 150)), gain = (.05 + .16 * S.fog); segsW.length = 0; if (on) for (var i = 0; i < lit.length; i += step) { var L = lit[i]; segsW.push([[B.APERT.x, B.APERT.y, B.APERT.z], [(L[0][0] / WW - .5) * 8, 2.2 + (.5 - L[0][1] / WH) * 5, -5], [L[1][0] / 255 * gain, L[1][1] / 255 * gain, L[1][2] / 255 * gain]]); } beamsOut.set(segsW, 1);
    // caminho óptico interno
    var arm = S.power && (S.key || S.mode === "splash"), opn = S.lock && !S.shut, segsI = O.segments(arm, opn, S.lim, gpos).map(function (s) { return [[s[0][0], s[0][1] + .314, s[0][2]], [s[1][0], s[1][1] + .314, s[1][2]], s[2]]; }); beamsIn.set(segsI, 1.2); beamsOut.tick(t); beamsIn.tick(t);
    O.shutter.rotation.y += (((arm && opn) ? 1.2 : 0) - O.shutter.rotation.y) * Math.min(1, dt * 12); O.mirX.rotation.y = -Math.PI / 4 + gpos[0] * .1; O.mirY.rotation.z = gpos[1] * .1;
    ["r", "g", "b"].forEach(function (k) { O.lens[k].m.material.color.setHex(arm ? O.lens[k].c : 0x111111); });
    proj.material.opacity = S.power ? 1 : 0; B.emLed.material.color.setHex(arm ? 0xff2a1a : 0x2a0a08); B.led1.material.color.setHex(S.net.sacn || S.net.artnet ? 0x38ff5c : 0x0a2a10); B.led2.material.color.setHex((S.net.ndi || S.net.spout) && Math.floor(t * 6) % 2 ? 0xffb000 : 0x2a1e00);
    B.keyM.rotation.z += ((S.key ? Math.PI / 2 : 0) - B.keyM.rotation.z) * Math.min(1, dt * 8); B.lockPlug.position.z += ((S.lock ? 0 : .022) - B.lockPlug.position.z) * Math.min(1, dt * 6); B.rocker.rotation.x = S.power ? -.22 : .22; B.blades.rotation.z += dt * (S.power ? 24 : 0);
    puffs.forEach(function (p) { p.position.x += p.userData.v[0] * dt; p.position.y += p.userData.v[1] * dt; if (p.position.x > 3) p.position.x = -3; if (p.position.x < -3) p.position.x = 3; p.material.opacity = .02 + .06 * S.fog; });
    S.temp += ((live() ? 42 : 31) - S.temp) * dt * .05; pino.update(dt, mouse, W, H);
    var f = S.show[S.frame], F = fps(); $("#st1").textContent = (S.kpps / 1000).toFixed(0) + " kpps · " + (f ? f.length : 0) + " pts · " + (F ? F.toFixed(0) : "–") + " fps de frame"; $("#st1").style.color = F && F < 25 && live() ? "#FF2A1A" : "#38FF5C"; $("#st2").textContent = "frame " + (S.frame + 1) + " / " + S.show.length + " · " + S.name + " · DMX " + S.dmx; $("#warn").textContent = "PERIGO · LASER CLASSE 4 · 10 W · NÃO OLHE PARA O FEIXE · " + (!S.power ? "DESLIGADO" : S.mode === "splash" ? "FEIXE LIBERADO" : live() ? "FEIXE LIBERADO" : !S.key ? "DESARMADO" : !S.lock ? "SCAN FAIL" : "FEIXE ESTACIONADO"); $("#warn").style.color = live() || S.mode === "splash" ? "#FFB000" : "#FF2A1A"; $("#keyb").textContent = "CHAVE: " + (S.key ? "ARMADO" : "DESARMADO"); $("#keyb").classList.toggle("on", S.key);
    if (S.mode === "play") tips(); composer.render(); requestAnimationFrame(tick); }

  /* ---------- voto ---------- */
  var state = { savedAt: null }; try { var v = JSON.parse(localStorage.getItem("sc-moodboard-r5") || "null"); if (v) state = v; } catch (e) {}
  document.querySelectorAll(".opts").forEach(function (g) { var q = g.dataset.q; g.querySelectorAll("button").forEach(function (b) { if (state[q] === b.dataset.v) b.classList.add("on"); b.addEventListener("click", function () { state[q] = b.dataset.v; g.querySelectorAll("button").forEach(function (x) { x.classList.toggle("on", x === b); }); blip(1000); }); }); });
  if (state.notas) $("#notas").value = state.notas;
  var dbp = (window.claude && claude.use) ? claude.use("db").catch(function () { return null; }) : Promise.resolve(null);
  $("#save").addEventListener("click", function () { state.notas = $("#notas").value; state.savedAt = new Date().toISOString(); try { localStorage.setItem("sc-moodboard-r5", JSON.stringify(state)); } catch (e) {} $("#saved").textContent = "salvo · " + new Date().toLocaleString("pt-BR"); chord(); dbp.then(function (db) { if (!db) return; return db.doc("moodboard/round5").set(state); }).then(function () { $("#saved").textContent += " · na nuvem"; }).catch(function () {}); });

  /* ---------- boot: câmera mirada no output; o foco sai do ponto estático e vai para a parede ---------- */
  document.fonts.ready.then(function () { size(); var ol = ILDA.outlines([["SPELLCASTER", "64px Michroma", 272], ["LASER", "64px Michroma", 372]], WW, WH); SP.loops = ol.loops; SP.len = ol.len;
    var h = location.hash; if (h === "#laser" || h === "#tras" || h === "#dentro" || h === "#orq") { CAM.setView(VIEWS.rear[0], VIEWS.rear[1], true); start(); if (h === "#laser" || h === "#dentro") { S.key = true; $("#cams [data-a='cam.show']").disabled = false; if (h === "#laser") setCam("show"); } if (h === "#dentro") setCam("inside"); if (h === "#orq") PANELS.orq(); }
    else { CAM.setView(VIEWS.wall0[0], VIEWS.wall0[1], true); setTimeout(function () { setCam("wall", 2.6); }, 300); S.t0 = performance.now(); }
    requestAnimationFrame(tick); });
})();
